parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:react/recommended
  # - plugin:flowtype/recommended

plugins:
  - react
  # - flowtype

env:
  browser: true
  node: true
  es6: true

rules:
  semi:
    - error
    - never
  curly:
    - error
  no-var:
    - error
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  no-console:
    - off
  no-debugger:
    - off
  no-unused-vars:
    - error
  react/prop-types:
    - off
